# Generated by Django 5.1.4 on 2024-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom ou description de la connexion', max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('database_name', models.CharField(help_text='Nom de la base distante', max_length=100)),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
